apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-vdlq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-vdlq
    app.kubernetes.io/part-of: build-suite-test-application-mgck
  name: test-annotations-vdlq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-vdlq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-vdlq
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-fscf-tenant/build-suite-test-application-mgck/test-annotations-vdlq@sha256:9a5052ee24414a7f16708f7d4f70ed157a845d60934c6491ea67c5a3796f1fda
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
